### ISSUE TITLE
Add more logging for interactions

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/web-vitals-extension#109]
To help debug INP issues, add the ability to log info about each interaction, similar to the feature that logs layout shifts.

@mmocny

**Comment by mmocny** [comment]
Will do.

One caveat: at the moment, web-vitals.js does not have a way to report every-single-interaction.  You can only get a final INP report, or every change to the metric reported (i.e. every new highest).

What we want for logging is every interaction above a certain threshold (16ms? 50ms? 100ms?).  This is really easy to do just using the Event Timing API directly.

**Comment by brendankenny** [comment]
PR in https://github.com/GoogleChrome/web-vitals-extension/pull/120
