### ISSUE TITLE
Unable to turn on Console Logging for Incognito Mode

### ISSUE THREAD

**Issue by monsuj** [GoogleChrome/web-vitals-extension#125]
**Before you start**
Please take a look at the [FAQ](https://github.com/GoogleChrome/web-vitals-extension#faq) as well as the already opened issues! If nothing fits your problem, go ahead and fill out the following template:

**Describe the bug**

Unable to enable "Console Logging" debug option in incognito window. 
Hence Detailed Debug information like LCP CLS etc is not available in Console while using incognito mode. 

**To Reproduce**
Steps to reproduce the behavior.
Open chrome in incognito
Right click on Web Vitals Extension
Go to Option
This will open WebVital Extension option for Regular browser and NOT Incognito browser
Hence Detailed Debug information like LCP CLS etc is not available in Console while using incognito mode. 

**Expected behavior**
Either opening "option" in in cognito should open Separate option window
Or same option window should be applicable for both Normal & Incognito sessions. 

**Version:**

- OS w/ version: [e.g. iOS 13] Windows 11
- Browser w/ version [e.g. Chrome 81] Chrome: Version 113.0.5672.64 (Official Build) (64-bit)

**Additional context, screenshots, screencasts**

**Comment by tunetheweb** [comment]
> Or same option window should be applicable for both Normal & Incognito sessions.
The same window is applicable in both Normal & Incognito sessions.

Here's what I see once I enable the extension in incognito mode
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/10931297/236779395-287e8fac-91e4-4dd7-8b37-f098bf2add15.png">

Turning off console logging in that options screen in Normal mode, also affects the incognito mode (note sometimes you have to reload a couple of times to ensure the new options have taken effect).

Is this not what you are seeing?
