### ISSUE TITLE
webvitals query

### ISSUE THREAD

**Issue by dbeaver12** [GoogleChrome/web-vitals-extension#129]
Hi..
With ref to a ticket raised on MMU system (71365077), we would like to check on these prior to use in Manchester Metropolitan university one of our departments-
**When was software last updated
Is software still on active development
Are the software provider committed to patching the software in event of security incident or known security vulnerabilities.**

**Our Information security dept checked on this one as urgent -Please update us on this –

The chrome add-on page states that data is not sold to 3rd parties, outside of approved use cases. Please help us  to understand what data (if any) would be sold, and the used cases for selling this data.**

Please could answer the above-mentioned question about the **Web Vitals**.

Thanks, and Regards,
Jesu

Jesu Mathew 
Software Licensing Administrator

**Comment by tunetheweb** [comment]
When was software last updated: **Last week**
Is software still on active development: **Yes**
Are the software provider committed to patching the software in event of security incident or known security vulnerabilities.: **Yes**

> The chrome add-on page states that data is not sold to 3rd parties, outside of approved use cases. Please help us to understand what data (if any) would be sold, and the used cases for selling this data.**

Please explain where you saw this. Data is only collected locally by the extension and presented to the user. No data is collected reporting, though the extension does make an API call to request additional data from our public CrUX API.
