### ISSUE TITLE
What % of my browsing hits vs. doesn't?

### ISSUE THREAD

**Issue by dalmaer** [GoogleChrome/web-vitals-extension#13]
I am enjoying looking at a scoreboard and peaking at the overall view of things.

One idea would be to have an option to show meta information such as:

- % of runs (final) scores that hit vs. don't
- top 5 / bottom 5 list (not sure the right numbers, if they reset each week etc)

**Comment by tunetheweb** [comment]
Since this issue was raised we added CrUX data to allow you to see experiences from other users. Given that, I think measuring multiple local experiences is less important and in fact may actually be more confusing.

So I think we should close. WDYT?
