### ISSUE TITLE
Why is there no web-vitals option in devtools' performance, and display the web-vitals value in timing?

### ISSUE THREAD

**Issue by zengzuo613** [GoogleChrome/web-vitals-extension#164]
I am using Chrome 116.0.5845.188 now. Previously, the web-vitals plugin could be selected in devtools, and web-vitals values were displayed in timing. Why is it gone now? Is it because my configuration is incorrect?

# Previously
![image](https://github.com/GoogleChrome/web-vitals-extension/assets/76633368/fa7b3b8f-4261-4870-99cb-a5972658a246)

# Now 
![image](https://github.com/GoogleChrome/web-vitals-extension/assets/76633368/205760e5-8497-4631-9a09-6e730c56fe3c)

**Comment by tunetheweb** [comment]
This is not to do with the Web Vitals Extension that this repo is for, but is part of DevTools.

The [Web Vitals track was removed in Chrome 114](https://developer.chrome.com/blog/new-in-devtools-114/#web-vitals). It duplicated a lot of data that was already available in the Timings and Experience/Layout Shifts track. Those tracks also provided additional information when those timings were clicked on, that the Web Vitals track did not, so they were better than the Web Vitals track. So to avoid the duplication and consolidate on the better option, we removed the Web Vitals track.
