### ISSUE TITLE
FID should only be considered passing (green) when it's state is final

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web-vitals-extension#19]
Feedback from Phil: 

> I wouldn't show a green 0.00 for FID prior to the first input. I'd show a gray "--" or something like that since 0.00 is a valid value after an input, and seeing green is confusing.

The fix here will be only considering FID to be passing when it's state is final.

**Comment by tunetheweb** [comment]
Think this is an old issue as it currently shows gray/“waiting for input” for FID and INP but leaves the overall status as Green if the other CWVs pass.

I think given it’s always a state in time measure, that’s fair enough and so we can close this?
