### ISSUE TITLE
Extension freezes when a page is refreshed with throttling

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/web-vitals-extension#27]
**Repro Steps**

- Navigate to https://www.theverge.com/
- Click on the page to trigger FID
- Open the extension to observe the metrics, note their values
- Open DevTools on the page and enable Fast 3G throttling
- Refresh the page and wait for it to load
- Open the extension to observe the metrics, note none of their values have changed and they all read "final", even CLS
- Repeat the refresh as many times as you like without changes.
- Disable Fast 3G throttling
- Refresh the page and wait for it to load
- Open the extension to observe the metrics, note their values change again

**Other Notes**
- If I switch tabs and go back to the throttled tab, the metric values appear correctly again.
- Sometimes I'll even see an LCP of 0.00 s
![image](https://user-images.githubusercontent.com/2301202/80753048-3ab6d200-8af2-11ea-8d42-ae2afd712e3a.png)

**Related Issues**
It'd be great if the URL and timestamp of the page load the metrics were from was listed in the extension, it was hard to tell on refresh if the numbers were actually current or not.

**Comment by rviscomi** [comment]
This appears to be resolved. Closing 👋
