### ISSUE TITLE
Badge closes do not fully persist

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web-vitals-extension#38]
The current badge overlay close button will remove the badge from the page, but will not persist the badge closure during your session. This might be surprising to developers (e.g I see my metrics -> close badge -> CLS wasn't final and just updated -> whoops here's the badge again).

Few options....

1. Clicking close will be the same as disabling the overlay for the particular tab (i.e we update your overlay preferences on clicking 'Close' and you have to go back to the Options to re-enable it). I think this would be the simplest option.
2. Clicking close has some session awareness. If you reload the page or come back later, we'll bring back the overlay. I'm currently thinking 1 might be sufficient.

@housseindjirdeh interested in taking this one when you have time?

**Comment by housseindjirdeh** [comment]
Yep I can take this on!

Related, but I also noticed switching tabs and returning will always re-surface the overlay (close badge -> switch tab -> come back to original tab -> badge overlay is back). This may be intended, but I found it kind of unexpected.

Agreed, option 1 sounds simplest 👍

**Comment by tunetheweb** [comment]
My personal view, with the popup overlay option now is that people can use that if they don't want it to persist and HUD if they do want it to persist (with option to dismiss temporarily with the "Close" link).

So I vote to close this issue.
