### ISSUE TITLE
Global style overrides breaking old Facebook layout

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web-vitals-extension#44]
Report: https://twitter.com/unix_root/status/1257732387074535425/photo/1

Repro confirmation:

![image](https://user-images.githubusercontent.com/110953/81102201-22fd9600-8ec4-11ea-9076-5da123aab5f9.png)

**Comment by RByers** [comment]
I played about 10 rounds of poker on https://www.pokernow.club/ before I realized the 5th card was never showing as a result of this bug 😆. Or it could have been some other similar bug in recent versions of this extension - updating the extension for the past few days of commits fixed it. Clearly I'm a terrible poker player. Don't worry Addy, you don't owe me any money - somehow I won anyway 😮 .

**Comment by addyosmani** [comment]
@RByers If it's any consolation, here is a graph of my blood pressure before and after reading your last sentence 🤣

![37575284](https://user-images.githubusercontent.com/110953/81489809-0dbf9900-922f-11ea-8e59-9500c5fafcec.jpg)

Glad to hear the latest commits do the trick and congrats on winning! You're too good at poker to let rendering bugs hold you back 🥳

**Comment by RByers** [comment]
Hah hah. Yeah right, I'm SO good that I didn't even realize I was playing only 80% of the game 😉 . It was the third game I've played in my life.
