### ISSUE TITLE
Breaks gmail UI, when active

### ISSUE THREAD

**Issue by tapsboy** [GoogleChrome/web-vitals-extension#46]
Searchbox
![image](https://user-images.githubusercontent.com/868525/81111532-3b34db80-8eeb-11ea-9953-bad063d3fd2e.png)

Missing action checkbox
![image](https://user-images.githubusercontent.com/868525/81111569-4ab42480-8eeb-11ea-8c63-a9b08c8039b4.png)

**Comment by addyosmani** [comment]
Thanks. I'll address this as part of https://github.com/GoogleChrome/web-vitals-extension/issues/47 today.
