### ISSUE TITLE
[Feature] CrUX field data

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web-vitals-extension#53]
The extension currently provides a local view of your URL's Core Web Vitals metrics but it can also be valuable to get insight into aggregate field data for the URL too (e.g at an origin or URL-level). We will explore adding field data to the extension via CrUX.

Some considerations:

- Initial implementation will be behind a flag until we roll-out
- Only attempt to fetch information if we're not on localhost
- Attempt to match the field metrics UI in current PageSpeed Insights for distributions
- Expose an option for developers to turn off field data (as this will lengthen the drill-down UI)
- Utilize caching so we don't call the REST API too frequently
- Only expose field data in the drill-down, but not the overlay? (I guess given this data will not change during development it's less useful in the overlay?)

@rviscomi any other considerations?

**Comment by rviscomi** [comment]
One compelling use case is to highlight significant deviations in local data vs field data. For example, I'm a developer testing my website and the extension tells me my local vitals are all Good. Field data kicks in to remind me that my experience is an outlier and 90% of real user experiences are worse than mine.

There are also some considerations for the type of field data we want to get:
- URL data, origin data, or both
- desktop only to match the developer's own experience, or all devices combined
- detect the developer's ECT and request similar field data if applicable, or all ECTs combined

**Comment by Abukaleeed** [comment]
How?

**Comment by addyosmani** [comment]
@rviscomi Would it be possible to ask for a summary of where we are currently at with adding CrUX API support? (I saw the conversation about how to approach keys and am happy to chat through a solution for that specifically)

**Comment by rviscomi** [comment]
I've pushed my changes to the [`field-data`](https://github.com/GoogleChrome/web-vitals-extension/blob/field-data/src/browser_action/popup.js) branch. Could use some UI cleanup but it works for origin data now.

**Comment by rviscomi** [comment]
@addyosmani what direction do you want to take this feature? I think I've gone as far as I can without making too many UX assumptions.

**Comment by addyosmani** [comment]
Thanks for the reminder here, @rviscomi! Some thoughts:

*   Shall we align the UX for field insights with the current styles for CrUX data found in PSI?
*   \> cache results to avoid calling the API on subsequent popup reopenings - yes! That would be great to land before we make this generally available. 
*   \> "inline" each tri-color histogram next to the local metrics for easier comparison - I think this could be an interesting idea but would love to work with Jiwoong to see if there's a UX mock we think could work for it. For the MVP, how would you feel about us getting out a version closer to the current PSI UX?
*   \> request the URL first, and fall back to origin if it doesn't exist. I would be open to us doing this! I do think we would want to make it clear in the UI when this is happening so that its clear.

**Comment by addyosmani** [comment]
Thanks for the reminder here, @rviscomi! Some thoughts:

*   Shall we align the UX for field insights with the current styles for CrUX data found in PSI?
*   \> cache results to avoid calling the API on subsequent popup reopenings - yes! That would be great to land before we make this generally available. 
*   \> "inline" each tri-color histogram next to the local metrics for easier comparison - I think this could be an interesting idea but would love to work with Jiwoong to see if there's a UX mock we think could work for it. For the MVP, how would you feel about us getting out a version closer to the current PSI UX?
*   \> request the URL first, and fall back to origin if it doesn't exist. I would be open to us doing this! I do think we would want to make it clear in the UI when this is happening so that its clear.

**Comment by rviscomi** [comment]
New UI! Here's what I'll be implementing as part of this issue:

![image](https://user-images.githubusercontent.com/1120896/102527742-90cd8b00-406b-11eb-8f27-5ca27d850e06.png)
