### ISSUE TITLE
Error: Extension manifest must request permission to access this host

### ISSUE THREAD

**Issue by gtsiolis** [GoogleChrome/web-vitals-extension#54]
The following error is shown within the extension (Errors) page every time you open a new tab.

<img width="681" alt="Screen Shot 2020-05-08 at 11 25 55 AM" src="https://user-images.githubusercontent.com/120486/81388045-5e949c00-9120-11ea-9148-db71d9023249.png">

**Comment by romanadamita** [comment]
Same.
https://twitter.com/AdamitaRoman/status/1258680104143765505
