### ISSUE TITLE
Issue on src/browser_action/popup.js

### ISSUE THREAD

**Issue by romanadamita** [GoogleChrome/web-vitals-extension#55]
Just scanned with deepscan.io and found this issue: [https://deepscan.io/dashboard/#view=project&tid=9092&pid=11374&bid=168611&subview=issues&impact=%5B%22High%22%5D](url)

**Comment by romanadamita** [comment]
![image](https://user-images.githubusercontent.com/15194258/81390760-ac130800-9124-11ea-9da8-032e9002a8da.png)

**Comment by pedrommenezes** [comment]
I've been also seeing an error, but on `popup.html` file:
<img width="655" alt="Screenshot 2020-05-08 at 11 41 13" src="https://user-images.githubusercontent.com/36070274/81398297-debb0180-9120-11ea-8188-310c59bea654.png">
