### ISSUE TITLE
Release on Chrome web store?

### ISSUE THREAD

**Issue by transitive-bullshit** [GoogleChrome/web-vitals-extension#57]
I know it's a preview, but this will be a significant barrier to adoption for many developers.

Also, once it's on the web store, I'd suggest adding a large, obvious CTA to both the homepage and the readme. Right now, the homepage is lacking a clear CTA to get started with the extension which is the flow that 95% of people will want to take.

Cheers 😄

**Comment by addyosmani** [comment]
Thanks for asking about this. I've covered it in our README: https://github.com/GoogleChrome/web-vitals-extension#faq. The tl;dr is that we're working with the Chrome Web Store to get the extension submitted but extensions authored by Googlers need to go through additional privacy and security reviews, this the delay. Hoping to get this over there as soon as possible! 😄

**Comment by jdiamond** [comment]
Can we keep this issue open until it's published so we can subscribe to the issue to know when it's ready?
