### ISSUE TITLE
Uncaught (in promise) ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by MattixNow** [GoogleChrome/web-vitals-extension#58]
An error appear after i installed the extension
![image](https://user-images.githubusercontent.com/32040951/81495308-a85fbc80-92af-11ea-8622-f99de275e921.png)

**Comment by addyosmani** [comment]
@MattixNow Could you share if this exception was causing badging or other features to stop working? I would love to determine if this was an error that happened in the background or if it broke the extension Ui entirely. Will take a look regardless.

Cheers!

**Comment by MattixNow** [comment]
Just after I installed the extension I've seen this error. No change in the ui

**Comment by MattixNow** [comment]
I've seen other error
![image](https://user-images.githubusercontent.com/32040951/81604990-118b2100-93d1-11ea-9cdb-b7a4c137dc4f.png)
