### ISSUE TITLE
Freezin meet.google.com

### ISSUE THREAD

**Issue by rafaelstz** [GoogleChrome/web-vitals-extension#59]
When participating in some meetings not just in meet.google.com the website is freezing and the points in the extension change a lot.
I would suggest avoiding the load in these scenarios or to have a toggle button to not load in some specific sites.

**Comment by addyosmani** [comment]
@rafaelstz Could you share what version of the extension you experienced this issue on? I recently landed some fixes in master to specifically limit the impact on sites like Google Meet (we throttle how often we badge CLS updates) but it's possible the version you're using was less recent or alternatively, I still have work to do there 😄 

Regardless, I'll take a second look with keeping the extension on when Meet is running in case we missed something.

**Comment by rafaelstz** [comment]
Nice @addyosmani I'm running the version 0.1.1

**Comment by kretjens** [comment]
Not sure if related: When I drop the `web-vitals-extension-master` folder on `chrome://extensions` I get this error message: 

![image](https://user-images.githubusercontent.com/8503760/82194263-cdc77880-98f6-11ea-9928-96ff3dabf4d6.png)

**Comment by addyosmani** [comment]
@kretjens Would you mind trying out https://chrome.google.com/webstore/detail/web-vitals/ahfhijdlegdabablpippeagghigmibma?hl=en

**Comment by addyosmani** [comment]
Hey folks. I've anecdotally heard reports from a number of people that having Google Meet open in a tab while the extension is installed has been causing them to see spikes in CPU. The extension should technically not run at all on Meet tabs - for example, here's the badging I see (neutral/disabled):

![image](https://user-images.githubusercontent.com/110953/82619545-139c6f00-9b8b-11ea-9e2a-ea4455b551de.png)

When I check Chrome's Task Manager, I also haven't been able to pinpoint a Meet tab with the extension as a cause of these issues.

Given version 0.2.0 (latest) has a number of fixes that aimed to address previous issues with sites that would cause frequent badging, I'm going to close this issue for now. 

If folks would like to test with 0.2.0, I'm happy to take a bug report with a reproduction if you're still seeing issues when having Meet open.  Thanks!
