### ISSUE TITLE
SPA sites - New Pages Metrics

### ISSUE THREAD

**Issue by dwsmart** [GoogleChrome/web-vitals-extension#63]
**Describe the bug**
The first initial visit to an SPA site it fine, but if you go to a new page handled by an internal router (i.e. the page is hydrated without a reload) the subsequent page views stack up in the metrics, so you have a combined CLS of all page views, and seemingly the LCP & FID of the initial page.

**To Reproduce**
Go to any SPA that works this way and click around, monitoring the figures.

**Expected behavior**
It would be great if the route change could be detected and the metrics adjusted accordingly.

**Version:**

- OS w/ version: Windows 10
- Browser w/ version: Chrome 83

**Comment by rviscomi** [comment]
This is a limitation of the web platform primitives and unfortunately the extension can't do much if anything to alleviate it. The WebPerf WG is actively looking at ways to better measure use cases like SPAs.

**Comment by dwsmart** [comment]
Thank you for he feedback @rviscomi 

Hopefully they will come up with something around this. Fingers crossed 🤞
