### ISSUE TITLE
[Memory usage] Background script

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web-vitals-extension#71]
**Describe the bug**

It looks like we may have some additional memory leaks sitting around 🚿  Once all tabs that are badged are closed, memory usage from the extension remains in the ~50MBs on my machine. 

<img width="592" alt="Screen Shot 2020-06-23 at 6 42 59 PM" src="https://user-images.githubusercontent.com/110953/85487560-aa40bf00-b581-11ea-87ac-2174ecc8f2d0.png">

This continues to grow if left open for a few minutes.

![image](https://user-images.githubusercontent.com/110953/85487594-bd538f00-b581-11ea-9e4e-cc701584c5ae.png)

**To Reproduce**

1. Open four tabs in sequence - web.dev, cnn.com, theverge.com, disney.com
2. Wait for the tabs to fully load
3. Measure extension's memory consumption and CPU utilization using Chrome's Task Manager
4. Close all open tabs except about:extensions
5. Measure extension's memory consumption and CPU utilization using Chrome's Task Manager

This appears to also be present after #68 and #69 cc @patrickhulce as an fyi

**Comment by patrickhulce** [comment]
> Measure extension's memory consumption and CPU utilization using Chrome's Task Manager

This is the part of this I don't trust here :) Every time I inspected the extension itself with DevTools all memory usage was low and/or eventually GC'd after #69 

While the memory does grow for a few minutes in Chrome's task manager. It all appears to be the virtual DOM elements/listeners created by Chrome extension APIs and the periodic checking the extension does and can all be GC'd. (notice the enormous cliff after nodes hit ~600)
![image](https://user-images.githubusercontent.com/2301202/85581752-79ed3500-b602-11ea-96ed-447d959ef88d.png)

There is some cleanup we can do for ending animations earlier though.
