### ISSUE TITLE
Extension breaks chromestatus

### ISSUE THREAD

**Issue by npm1** [GoogleChrome/web-vitals-extension#72]
**Describe the bug**
When the extension is enabled and I am logged in on https://www.chromestatus.com/feature/5167290693713920, I cannot see the 'star', 'file a bug', or 'edit' buttons. Once I disabled the extension and refresh, I am able to see those buttons.

**Version:**

- OS w/ version: MacOS Catalina
- Browser w/ version Chrome 83

**Comment by addyosmani** [comment]
@npm1 Thank you for filing this issue. I've attempted to repro this issue using M83 and M85, both with the current stable version of the extension and the version in master. It appears ChromeStatus is rendering as one would expect. Please see screenshots below.

Would it be possible to share if the version you used was installed from Chrome Web Store? https://chrome.google.com/webstore/detail/web-vitals/ahfhijdlegdabablpippeagghigmibma?hl=en. There definitely were issues with style scoping leaks causing issues like this in earlier, alpha versions of the extension. We addressed these before pushing to the web store (or so we thought).

M83 (stable version of extension from store):

<img width="1552" alt="Screen Shot 2020-06-25 at 5 58 58 PM" src="https://user-images.githubusercontent.com/110953/85809784-e143db80-b70d-11ea-8590-0cf8cdf27679.png">

M85 (stable version of extension):

<img width="1364" alt="Screen Shot 2020-06-25 at 5 57 25 PM" src="https://user-images.githubusercontent.com/110953/85809770-dab56400-b70d-11ea-942d-f9c111f0a329.png">

M85 (master/bleeding edge version of extension)

<img width="1364" alt="Screen Shot 2020-06-25 at 5 57 57 PM" src="https://user-images.githubusercontent.com/110953/85809788-e3a63580-b70d-11ea-85e7-b8f0ded6bb84.png">

**Comment by npm1** [comment]
Looks like I was using version 0.1.0. I removed that and installed the ones you linked above and this is no longer an issue. Thanks!

**Comment by addyosmani** [comment]
👍
