### ISSUE TITLE
Chrome error - unable to unzip extension

### ISSUE THREAD

**Issue by danparm** [GoogleChrome/web-vitals-extension#81]
Noticed a problem with the extension this morning in the console, unable to load a dependent script. Removed the extension to install 0.4.1 from the Chrome Web Store and I'm getting an error than the extension can't be unzipped.
![image](https://user-images.githubusercontent.com/4818190/101813362-a29eb380-3aea-11eb-85b5-3c346d14379b.png)

Win10 Version	10.0.17134 Build 17134
Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by addyosmani** [comment]
Thank you for filing this issue. 

I attempted to publish a new release this week and discovered that the zip output we usually upload was not being recognized for reasons I am still debugging. I've gone ahead and submitted a reverted release to Chrome Web Store which I am hopeful gets accepted in the mean time and should at least make the above warning disappear.

**Comment by danparm** [comment]
@addyosmani got the extension re-installed this morning. No issues with the install or regular usage so far. Thanks!

**Comment by gnechita-toptal** [comment]
@addyosmani I was recently getting the `Metrics data unavailable.` message and tried to reinstall the Web Vitals extensions via Chrome but I'm getting a Zip error message now.

![image](https://user-images.githubusercontent.com/57177990/107353856-31718180-6ad6-11eb-8dba-3f62775ea926.png)

Any idea on what could I do to reinstall the extension?

MacOS Big Sur 11.2 (20D64)
Version 88.0.4324.146 (Official Build) (x86_64)

**Comment by addyosmani** [comment]
The fix for the above is in flight and should automatically fix itself once the Chrome Web Store approves the release. In the mean time, I would recommend installing from the repo.

Context: This was my fault - I attempted to push the latest version to 10% of our users last night but there appear to still be some issues in getting the Chrome Web Store unzipping it.

**Comment by addyosmani** [comment]
This should now be fixed https://chrome.google.com/webstore/detail/web-vitals/ahfhijdlegdabablpippeagghigmibma. Could someone confirm they can install?

**Comment by gnechita-toptal** [comment]
> This should now be fixed https://chrome.google.com/webstore/detail/web-vitals/ahfhijdlegdabablpippeagghigmibma. Could someone confirm they can install?

@addyosmani the installation via Chrome Web Store works now. Thanks for the help Addy!

**Comment by bugushi** [comment]
> This should now be fixed https://chrome.google.com/webstore/detail/web-vitals/ahfhijdlegdabablpippeagghigmibma. Could someone confirm they can install?

hi, I ran into the same problem, can you share the solution?

**Comment by rviscomi** [comment]
Closing out this issue. Let us know if this happens again to anyone, but as a workaround if needed you can side load the extension from source.
