### ISSUE TITLE
Colours Red or green as an indicator for good or bad should be changeable for colour blind people

### ISSUE THREAD

**Issue by transafrika** [GoogleChrome/web-vitals-extension#84]
As a so called colour blind person i cant see the difference between the default colors red and green indicating fast or slow loading of a page so it would be very helful if the colours could be changed in the preferences to lets say red and blue. 8% of the male population and 0,5% of all woman have this "red and green problem". https://en.wikipedia.org/wiki/Color_blindness

**Comment by rviscomi** [comment]
We could have a setting on the Options page to use a different color scheme.

**Comment by tunetheweb** [comment]
There are other indicators for failing web vitals, so it’s not _just_ based on colors:
- Badge cycles through all failing status’s giving the value when not all three are passing
- Pop up indicates which category the current value falls in
- HUD has a square icon for needs improvement and a triangle for poor
- Console logging indicates status

**Comment by tunetheweb** [comment]
Maybe we should change the green square to a circle to make this more obvious on the badge when there are no issues?
