### ISSUE TITLE
[Feature request] Blinking icon is too distracting. Having an option to disable it might be nice.

### ISSUE THREAD

**Issue by gangsthub** [GoogleChrome/web-vitals-extension#89]
Initial state:
<img alt="initial state, only red squared icon" src="https://user-images.githubusercontent.com/6775220/120507384-0da8b300-c3c7-11eb-8f0d-8cb5f558b0d6.png" />
Alternate state:
<img alt="alternate state, req square is covered by some more data, like the metric failing and the offset value"  src="https://user-images.githubusercontent.com/6775220/120507440-1a2d0b80-c3c7-11eb-9ec1-aa6c3f83422a.png" />

Currently, the badge is [designed](https://github.com/GoogleChrome/web-vitals-extension/blob/4d51b39e54a5199d9aa09fd6ae3c75fd7d03008b/src/bg/background.js#L240) to be blinking constantly.

It's a little bit too distracting when the Extension icon is "pinned" on Chrome's toolbar.

I think having the blinking as an option you can disable would be more friendly. Or just show the red icon with the badge (one of the current states).

**Comment by rviscomi** [comment]
I wonder if we can tap into the [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) user setting to improve this. The popup also has a slight animation that we can skip.

**Comment by tunetheweb** [comment]
I kinda agree it's a bit distracting and had a quick look into this, but might not be as simple as I initially thought it would be.

This is controlled by the service worker, but it doesn't have access to `localStorage` (to get the user settings), nor `window` (to call `window.matchMedia('(prefers-reduced-motion: reduce)').matches` to see if `prefers-reduce-media` is set).

So guessing we'll need to broadcast the latest state of this with each metric? Which sounds a little more complicated than ideal.

Or maybe we should just stop this and stick with the overall state one (which should only change when the metric worsen - which is probably something you want to be altered to).

**Comment by tunetheweb** [comment]
Actually the settings are synced to profile, so are available to the service worker. Fix coming up.
