### ISSUE TITLE
[Bug] TypeError - extension not working

### ISSUE THREAD

**Issue by lakssrini** [GoogleChrome/web-vitals-extension#91]
**Describe the bug**
I just reinstalled the extension and upgraded to v1.0.0. The extension has stopped working on all pages with a `TypeError: Failed to fetch dynamically imported module`. Previous installs were working.

**To Reproduce**
I got the latest master.zip, loaded the extension from source - it failed with the same error reported below. 
Removed it and then installed v1.0.0 from chrome store - load any page.

**Expected behavior**
Web Vitals to work

**Version:**
Extension version - 1.0.0
- OS w/ version: MacOS 11.4
- Browser w/ version Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Additional context, screenshots, screencasts**
<img width="700" alt="Screen Shot 2021-06-24 at 11 33 36 AM" src="https://user-images.githubusercontent.com/42414883/123315209-52b09880-d4e0-11eb-9ed4-80c79a206785.png">
<img width="453" alt="Screen Shot 2021-06-24 at 10 10 29 AM" src="https://user-images.githubusercontent.com/42414883/123315214-53e1c580-d4e0-11eb-9de5-ff1de5219654.png">

**Comment by smerriman** [comment]
Same here. Extension seems completely broken at the moment.

**Comment by addyosmani** [comment]
Apologies about this. I'll be publishing a hotfix for this release asap.

**Comment by addyosmani** [comment]
1.0.1 should be published to the store and available to everyone now:

![image](https://user-images.githubusercontent.com/110953/123371986-95518f80-d537-11eb-97c1-6c2bd586cbe8.png)

Can you close the bug if it works for you?

**Comment by lakssrini** [comment]
It works now. Thanks @addyosmani !
