### ISSUE TITLE
First input delay permanently 'waiting for input'

### ISSUE THREAD

**Issue by smerriman** [GoogleChrome/web-vitals-extension#93]
The First input delay metric never says anything other than 'waiting for input' on all websites.

Not sure if this is caused by the recent bug that broke the extension entirely, but I see you had exactly the same issue in the screenshot you provided: https://github.com/GoogleChrome/web-vitals-extension/issues/91#issuecomment-868204912

**Version:**

- OS w/ version: Windows 10
- Browser w/ version: Chrome 91

**Comment by rviscomi** [comment]
I'm looking into this. After a few tests I can reproduce the issue.

**Comment by smerriman** [comment]
1.02 has not fixed this issue. The HUD continues to show 'waiting for input'.
