### ISSUE TITLE
WebVitals measures different LCP than Google Lighthouse

### ISSUE THREAD

**Issue by SkaiiiDSO** [GoogleChrome/web-vitals-extension#96]
Hi all,

i've come across following Bug with the WebVitals-Extension

**Describe the bug**
When Running a Lighthouse-Test on a Webpage and viewing the Web Vitals through the WebVitals Extensions the resulting LCP in Lighthouse and WebVitals-Extension differs in some Cases.
EDIT: This seems to happen on mostly clientside rendered pages (for example: https://www.imwalking.de/damenschuhe/pumps/#als=true&highlight=98130727)

**To Reproduce**

- Open up a clientside rendered webpage 
- Make sure to have the WebVitals-Extension installed
- Run a Lighthouse-Test
- After the Testrun is complete, make sure that lighthouse doesn't reload the page again. (If it does, repeat the Lighthouse-Test)
- Then Open your Web-Vitals-Extension and Compare Lighthouse Result to the Web-Vitals-Extension

**Expected behavior**
Largest-Contentful-Paint Values should be equal in the Web-Vitals-Extension and Lighthouse-Reports

**Version:**

- OS w/ version: Windows 10 (19043.1110)
- Browser w/ version: Chrome 91.0.4472.164 & Chrome 92.0.4515.107 

**Additional context, screenshots, screencasts**
![Screenshot 2021-07-23 122637](https://user-images.githubusercontent.com/87857373/126772777-b24b0a2b-a0df-449c-8d08-7c748d9befc1.jpg)

**Comment by rviscomi** [comment]
Not sure this is a bug with the extension, as its CWV data is based on the web-vitals.js library. AFAIK Lighthouse uses the native APIs directly and not the wv library so that may be a source of discrepancy. cc @philipwalton @paulirish

**Comment by paulirish** [comment]
Lighthouse's LCP (as of 8.0) includes all subframes, too. (matching CrUX). 
As I'm guessing the extension doesn't also gather the values from subframes, this may explain the discrepancy. 

If it's not a matter of subframes, this is unexpected. (I'm 85% sure our time origin definitions match up, but that'd be my next guess)

**Comment by rviscomi** [comment]
Seems like this is WAI. Closing.
